
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('stations').del()
    .then(function () {
      // Inserts seed entries
      return knex('stations').insert([
        {id: 1, name: 'CFCR',
        audio_feed: 'http://onair.cfcr.ca/hifi.mp3',
        home_page: 'http://cfcr.ca/',
        city: 'Saskatoon',
        province: 'SK',
        description: 'CFCR 90.5 FM Community Radio is a non-profit corporation owned by the Community Radio Society of Saskatoon. We are a volunteer powered, listener supported organization serving the alternative radio needs of Saskatoon and surrounding areas.',
        frequency: '90.5 FM',
        language: 'English',
        stream_type: 'audio/mp3'
      },
       {
        id: 2,
        name:'CFMU' ,
        audio_feed: 'http://138.197.136.105:8000/mount.128mp3' ,
        home_page:'http://cfmu.ca/' ,
        city: 'Hamilton',
        province:'ON',
        description:'93.3 CFMU-FM, Canada’s third oldest campus / community radio station, has been redefining radio for over 25 years, delivering daily the most enlightening, innovative and entertaining programming in our broadcast area.',
        frequency: '93.3 FM',
        language:'English' ,
        stream_type: 'audio/mp3'
      },
      {
        id: 3,
        name: 'CKUW' ,
        audio_feed: 'http://shout.mtl.gameservers.com:9025/;stream.nsv&type=mp3' ,
        home_page: 'https://ckuw.ca',
        city:'Winnipeg' ,
        province:'MB',
        description: 'Since the early 60′s CKUW has offered students and the community a unique chance to express ideas and be introduced to music heard nowhere else in Winnipeg. CKUW programmers have an outspoken passion for music and information.',
        frequency: '95.9 FM' ,
        language: 'English' ,
        stream_type: 'audio/mp3'
      },
      {
        id: 4,
        name: 'CJSW' ,
        audio_feed: 'http://stream.cjsw.com/cjsw.mp3' ,
        home_page: 'http://cjsw.com',
        city:'Calgary' ,
        province:'AB',
        description: 'CJSW 90.9FM is Calgary’s community radio station, based at the University of Calgary. CJSW broadcasts music, spoken word and multicultural programming on 90.9FM and streaming online.',
        frequency: '90.9 FM' ,
        language: 'English' ,
        stream_type: 'audio/mp3'
      },
      {
        id: 5,
        name: 'CKCU' ,
        audio_feed: 'http://livestream.ckcufm.com/ckcu.mp3' ,
        home_page: 'https://www.ckcufm.com/',
        city:'Ottawa' ,
        province:'ON',
        description: 'On November 14, 1975, Canadian radio history was made. When the strains of Joni Mitchell’s “You Turn Me On, I’m a Radio” transmitted over the airwaves at 93.1 FM, CKCU became the first campus-based community radio station in the country.',
        frequency: '93.1 FM' ,
        language: 'English' ,
        stream_type: 'audio/mp3'
      },
      {
        id: 6,
        name: 'CIVL' ,
        audio_feed: 'http://198.162.116.249:8085/live.mp3' ,
        home_page: 'http://civl.ca/',
        city:'Abbotsford' ,
        province:'BC',
        description: 'CIVL Radio is a campus and community radio station that serves the University of the Fraser Valley (UFV), Abbotsford, Mission and Chilliwack.',
        frequency: '101.7 FM' ,
        language: 'English' ,
        stream_type: 'audio/mp3'
      },
      {
        id: 7,
        name: 'CHMR' ,
        audio_feed: 'http://mp3srv.munsu.mun.ca:8000/' ,
        home_page: 'http://www.mun.ca/chmr/',
        city:'St. John\'s' ,
        province:'NF',
        description: "Newfoundland's only alternative, broadcasting from the campus of Memorial University.",
        frequency: '93.5 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 8,
        name: 'CHUO' ,
        audio_feed: 'http://icecast1.isiglobal.ca:8000/chuo' ,
        home_page: 'http://chuo.fm/',
        city:'Ottawa' ,
        province:'ON',
        description: 'CHUO 89.1 FM is an independent, community-powered and listener - supported radio station.Since 1991, we’ve been proudly playing whatever we want.Not bound by a single genre of music, CHUO invites our listeners on a journey of discovery.',
        frequency: '90.9 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 9,
        name: 'CJLO' ,
        audio_feed: 'http://rosetta.shoutca.st:8883/stream' ,
        home_page: 'http://www.cjlo.com/',
        city:'Montreal' ,
        province:'QC',
        description: "CJLO is Concordia University's one and only radio station. 100% non - profit, and run almost entirely by volunteers, the station is located in the heart of the Loyola campus in the NDG borough of Montreal.",
        frequency: '1690 AM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 10,
        name: 'CKDU' ,
        audio_feed: 'http://archive1.ckdu.ca:9750/ckdu_1_on_air_high.mp3' ,
        home_page: 'http://www.ckdu.ca',
        city:'Halifax' ,
        province:'NS',
        description: "CKDU-FM is Halifax’s only FM campus-community radio station. We are a volunteer-run, 3200-watt station broadcasting from the Dalhousie campus to the metro Halifax area. CKDU-FM has been broadcasting as an FM station since 1985.",
        frequency: '88.1 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 11,
        name: 'CKXU' ,
        audio_feed: 'http://ckxu.uleth.ca:8000/stream/5/' ,
        home_page: 'http://ckxu.com/',
        city:'Lethbridge' ,
        province:'AB',
        description: "CKXU's mission is to showcase and promote cultural diversity in Southern Alberta. The team at CKXU creates and fosters an inclusive arts community that is accessible to everyone!",
        frequency: '88.3 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 12,
        name: 'CKUT' ,
        audio_feed: 'https://icecast.ckut.ca/903fm-192-stereo' ,
        home_page: 'https://ckut.ca/en',
        city:'Montreal' ,
        province:'QC',
        description: "CKUT is a non-profit, campus-community radio station based at McGill University. CKUT provides alternative music, news and spoken word programming to the city of Montreal and surrounding areas, 24 hours a day, 365 days a year.",
        frequency: '90.3 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 13,
        name: 'CITR' ,
        audio_feed: 'http://live.citr.ca:8000/live.mp3' ,
        home_page: 'http://www.citr.ca/',
        city:'Vancouver' ,
        province:'BC',
        description: "CiTR 101.9 FM is the broadcasting voice of the University of British Columbia, situated on the unceded, traditional Coast Salish territory of the Hən̓q̓əmin̓əm̓ speaking Musqueam peoples.",
        frequency: '101.9 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 14,
        name: 'CFMH' ,
        audio_feed: 'http://cfmh-listen.unbsj.ca:8000/1/;stream/1' ,
        home_page: 'http://localfm.ca/',
        city:'Saint John' ,
        province:'NB',
        description: "Local 107.3 FM - Listener Supported Community And Campus Radio In Saint John",
        frequency: '107.3 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 15,
        name: 'CFRC' ,
        audio_feed: 'http://audio.cfrc.ca:8000/;stream.nsv&type=mp3' ,
        home_page: 'http://www.cfrc.ca/',
        city:'Kingston' ,
        province:'ON',
        description: "CFRC 101.9FM is Kingston’s only campus & community radio station! We are a not-for-profit, volunteer-powered media outlet that fills the gap left by the mainstream.",
        frequency: '101.9 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 16,
        name: 'CFRU' ,
        audio_feed: 'http://archive.cfru.ca:8888/cfruhi2' ,
        home_page: 'http://www.cfru.ca/',
        city:'Guelph' ,
        province:'ON',
        description: "CFRU aims to provide a complete service to the community. We provide access to the media to groups and individuals who would otherwise have little access through mainstream media outlets.",
        frequency: '93.3 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 17,
        name: 'CFRO' ,
        audio_feed: 'http://192.99.20.78:9025/cfro_128k' ,
        home_page: 'http://www.coopradio.org/',
        city:'Vancouver' ,
        province:'BC',
        description: "Vancouver Co-operative Radio, CFRO, 100.5FM is a non-commercial, co-operatively-owned, listener-supported, community radio station.",
        frequency: '100.5 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 18,
        name: 'CFUR' ,
        audio_feed: 'http://142.207.5.73:8001/' ,
        home_page: 'http://cfur.ca/',
        city:'Prince George' ,
        province:'BC',
        description: "The 'FUR' (as it is known colloquially) is governed by the CFUR Radio Society, a non-profit corporation consisting of students and other community members who promote CFUR via membership drives, fundraisers, and on-air broadcasting.",
        frequency: '88.7 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 19,
        name: 'CHMA' ,
        audio_feed: 'http://chma-nicecast.mta.ca:8000/' ,
        home_page: 'https://chmafm.wordpress.com/',
        city:'Sackville' ,
        province:'NB',
        description: "CHMA 106.9 FM is owned and operated by the members of Attic Broadcasting Co. Ltd., a non-profit organization with its offices on the campus of Mount Allison University.",
        frequency: '106.9 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 20,
        name: 'CHOQ' ,
        audio_feed: 'http://podcast.servlinks.com/choq/lecture/choqliveaudio/1513139441635' ,
        home_page: 'http://www.choq.ca/',
        city:'Saint Catherine' ,
        province:'QC',
        description: "CHOQ's mission is to provide, through its radio activities, a voice to the University community of UQAM, in a spirit of discovery and diversity.",
        frequency: '' ,
        language: 'French' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 21,
        name: 'CHYZ' ,
        audio_feed: 'http://ecoutez.chyz.ca:8000/mp3' ,
        home_page: 'http://chyz.ca/',
        city:'Saint-Foye' ,
        province:'QC',
        description: "CHYZ 94,3 FM est, depuis 1997, la radio des étudiants de l’Université Laval de Québec.",
        frequency: '94.3 FM' ,
        language: 'French' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 22,
        name: 'CICK' ,
        audio_feed: 'https://usa13.fastcast4u.com/proxy/smithers?mp=/1' ,
        home_page: 'http://www.smithersradio.com/',
        city:'Smithers' ,
        province:'BC',
        description: "The Smithers Community Radio Society is an incorporated non-profit that manages a locally supported, volunteer operated community radio station (93.9FM).",
        frequency: '' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 23,
        name: 'CILU' ,
        audio_feed: 'http://luradio-server.lakeheadu.ca:8000/stereo128.mp3' ,
        home_page: 'http://www.luradio.ca/',
        city:'Thunder Bay' ,
        province:'ON',
        description: "Our mandate is to provide our listeners with high quality content that is not already found on the airwaves in Thunder Bay.",
        frequency: '102.7 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 24,
        name: 'CJLY' ,
        audio_feed: 'http://stream.cjly.net/' ,
        home_page: 'http://www.kootenaycoopradio.com/',
        city:'Nelson' ,
        province:'BC',
        description: "Kootenay Co-op Radio uses its facilities and the initiative and skills of its membership to create a medium for balanced expression of the varied perspectives of our community.",
        frequency: '93.5 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 25,
        name: 'CJMP' ,
        audio_feed: 'http://usa2.fastcast4u.com:3264/CJMP90.1FM' ,
        home_page: 'http://cjmp.ca/',
        city:'Powell River' ,
        province:'BC',
        description: "CJMP-FM is a Canadian radio station, which broadcasts at 90.1 FM in Powell River, British Columbia.",
        frequency: '90.1 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 26,
        name: 'CJRU' ,
        audio_feed: 'http://ryerson.out.airtime.pro:8000/ryerson_a?callback=?' ,
        home_page: 'http://www.thescopeatryerson.ca/',
        city:'Toronto' ,
        province:'ON',
        description: "CJRU 1280AM is Ryerson University's new campus and community multi-media hub. Our station airs a variety of programming from the university, Ryerson students, the community at large and from the NCRA Program Exchange.",
        frequency: '1280 AM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      },
      {
        id: 27,
        name: 'CFUV' ,
        audio_feed: 'http://cfuv.streamon.fm:8000/CFUV-64k.aac' ,
        home_page: 'http://www.cfuv.ca',
        city:'Victoria' ,
        province:'BC',
        description: "CFUV provides a platform for marginalized voices in our community to represent themselves on-air. We highlight music genres you won’t hear anywhere else.",
        frequency: '101.9 FM' ,
        language: 'English' ,
        stream_type: 'audio/aac'
      },
      {
        id: 28,
        name: 'CJSR' ,
        audio_feed: 'http://cjsr.streamon.fm:8000/CJSR-64k.aac' ,
        home_page: 'http://www.cjsr.com/',
        city:'Edmonton' ,
        province:'AB',
        description: "CJSR’s mission is to enlighten and entertain our audience through high quality and diverse programming that constantly challenges the status quo.",
        frequency: '88.5 FM' ,
        language: 'English' ,
        stream_type: 'audio/aac'
      },
      {
        id: 29,
        name: 'CFBX' ,
        audio_feed: 'http://thexaudio.tru.ca:8002/in/;?type=http&nocache=88%2Fstream.mp3&_=1' ,
        home_page: 'https://thex.ca/',
        city:'Kamloops' ,
        province:'BC',
        description: "CFBX-FM, also known as 'The X' 92.5 FM, is the campus radio station at Thompson Rivers University. They went live April 2001.",
        frequency: '92.5 FM' ,
        language: 'English' ,
        stream_type: 'audio/mpeg'
      }
      ]);
    });
};
